-- SQL Queries to implement Expected Delivery Date features
-- Run this in the Supabase SQL Editor

-- 1. Add expected_delivery_date to orders table if it does not exist
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS expected_delivery_date date;

-- 2. Add expo_push_token to profiles table if it does not exist
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS expo_push_token text;

-- 3. Create activity_logs table if it does not exist
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references public.orders(id) on delete cascade,
  user_id uuid references auth.users(id),
  message text not null
);

-- 4. Enable Row-Level Security (RLS) on activity_logs
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS policies for activity_logs
DROP POLICY IF EXISTS "Users can view activity logs" ON public.activity_logs;
CREATE POLICY "Users can view activity logs" ON public.activity_logs
FOR SELECT TO authenticated
USING (
  public.is_admin() OR 
  EXISTS (
    SELECT 1 FROM public.orders 
    WHERE orders.id = activity_logs.order_id 
    AND orders.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Authenticated users can insert activity logs" ON public.activity_logs;
CREATE POLICY "Authenticated users can insert activity logs" ON public.activity_logs
FOR INSERT TO authenticated
WITH CHECK (
  auth.uid() IS NOT NULL
);

-- 6. Grant authenticated admins permission to delete any order
DROP POLICY IF EXISTS "Admins can delete any order" ON public.orders;
CREATE POLICY "Admins can delete any order" ON public.orders
FOR DELETE
TO authenticated
USING (
  public.is_admin()
);

-- 7. Grant authenticated users permission to insert notifications (to notify admins/customers)
DROP POLICY IF EXISTS "Anyone can insert notifications" ON public.notifications;
CREATE POLICY "Anyone can insert notifications" ON public.notifications
FOR INSERT
TO authenticated
WITH CHECK (
  true
);

-- Grant admins permission to view all notifications, and users to view their own
DROP POLICY IF EXISTS "Users can select own notifications" ON public.notifications;
CREATE POLICY "Users can select own notifications" ON public.notifications
FOR SELECT
TO authenticated
USING (
  auth.uid() = user_id OR public.is_admin()
);
